version: "3.4"
services:
  backend:
    container_name: backend_test
    build:
      target: builder
    command: lein with-profile +test kaocha
    environment:
      - LOG_LEVEL=WARN

  postgres:
    container_name: postgres_test
    tmpfs:
      - /var/lib/postgresql/data
