version: "2"
services:
  server:
    build: .
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=postgres
    ports:
      - "3000:3000"

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:32790"
    volumes:
      - ./.pg-data:/var/lib/postgresql/data/

