name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v1
      - name: Build the stack
        run: docker-compose -f docker-compose.yml -f docker-compose-test.yml up